site_name: MinimalAgent
site_description: A lightweight agent framework for Amazon Bedrock
site_url: https://nipalm.github.io/minimalagent
repo_url: https://github.com/nipalm/minimalagent
repo_name: nipalm/minimalagent

docs_dir: docs

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.annotate
    - content.code.copy
    - search.highlight

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            heading_level: 2

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - Tools: guide/tools.md
    - Sessions: guide/sessions.md
    - Reasoning Display: guide/logging.md
    - Data Models: guide/models.md
    - Configuration: guide/configuration.md
  - Examples:
    - Basic Usage: examples/basic.md
  - API Reference:
    - Agent: api/agent.md
    - Models: api/models.md
  - Contributing: contributing.md
  - Changelog: changelog.md